debug: minor changes

diff --git a/bin/debug b/bin/debug
--- a/bin/debug
+++ b/bin/debug
@@ -3,21 +3,28 @@
 ## Debug Helper
 ## by Andriy Berestovskyy
 ##
+
+log () {
+    echo "    ${*}"
+}
+begin () {
+    echo "==> ${*}"
+}
+error () {
+    begin "Error ${*}"
+    exit 1
+}
 usage () {
-    if [ -n "$1" ]; then
-        echo "${0##*/} error: $1"
-    else
-        echo "Debug Helper"
-        echo "Usage:"
-        echo "    To attach to a running process:"
-        echo "    ${0##*/} <process_name> [regexp_to_backtrace]"
-        echo "        process_name  grep expression to find the process"
-        echo "    To analyse a core dump:"
-        echo "    ${0##*/} <core_dump>"
-        echo "        core_dump     core dump file"
-        echo "Example:"
-        echo "    ${0##*/} dpdk"
-    fi
+    echo "Debug Helper"
+    echo "Usage:"
+    echo "    To attach to a running process:"
+    echo "    ${0##*/} <process_name> [regexp_to_backtrace]"
+    echo "        process_name  grep expression to find the process"
+    echo "    To analyse a core dump:"
+    echo "    ${0##*/} <core_dump>"
+    echo "        core_dump     core dump file"
+    echo "Example:"
+    echo "    ${0##*/} dpdk"
     exit 1
 }
 
@@ -28,28 +35,27 @@ fi
 ## Try to open a core dump file
 CORE_DUMP="${1}"
 if [ -s "${CORE_DUMP}" ]; then
-    echo "Analyzing core dump ${CORE_DUMP}..."
+    begin "Analyzing core dump ${CORE_DUMP}..."
     binary=$(echo "q" | gdb /bin/ls "${CORE_DUMP}" 2>/dev/null | grep "Core was generated by" | cut -d '\`' -f 2 | cut -d "'" -f 1 | cut -d ' ' -f 1)
     if [ -z "${binary}" ]; then
-        echo "Error: file does not look like a core dump"
-        exit 1
+        error "analyzing core dump: ${CORE_DUMP} does not look like a core dump"
     fi
     if [ ! -f "${binary}" ]; then
-        echo "Error: binary file ${binary} not found"
-        exit 1
+        error "analyzing core dump: binary file ${binary} not found"
     fi
     gdb ${binary} ${CORE_DUMP}
     exit 0
 fi
 
-## Try to attach to a running process
-PROCESS=${1}
 
-PS=$(ps axww | awk '{print $1, $5}' | grep ${PROCESS} | head -1)
+PROCESS="${1}"
+begin "Attaching gdb to process ${PROCESS}..."
+
+PS=$(ps axww | awk '{print $1, $5}' | grep "${PROCESS}" | head -1)
 PID=$(echo "${PS}" | awk '{print $1}')
 PROG=$(echo "${PS}" | awk '{print $2}')
 if [ -z "${PID}" -o -z "${PROG}" ]; then
-    usage "Error attaching: process ${PROCESS} is not found"
+    error "attaching gdb: process ${PROCESS} is not found"
 fi
 
 shift
@@ -61,12 +67,12 @@ while [ "$#" -gt "0" ]; do
 done
 
 if [ -z "${BT}" ]; then
-    echo "Attaching gdb to ${PROG}[${PID}]"
+    log "attaching to ${PROG}[${PID}]..."
     gdb "${PROG}" "${PID}"
     exit 0
 fi
 
-echo "BT: ${BT} / ${PROG}"
+log "BT: ${BT} / ${PROG}"
 TMP_FILE=$(mktemp)
 readelf -s ${PROG} | grep ${BT} | awk '{
     if($4 == "FUNC" && $2 != 0) {
@@ -79,8 +85,8 @@ readelf -s ${PROG} | grep ${BT} | awk '{
         print "end";
         print "";
     }
-}' > ${TMP_FILE}
+}' > "${TMP_FILE}"
 
-echo "Attaching gdb to ${PROG}[${PID}] backtracing ${BT_PRINT}"
-gdb --command=${TMP_FILE} "${PROG}" "${PID}"
-rm -f ${TMP_FILE}
+log "attaching to ${PROG}[${PID}] backtracing ${BT_PRINT}"
+gdb --command="${TMP_FILE}" "${PROG}" "${PID}"
+rm -f "${TMP_FILE}"
